fix #1326 ClassCastException in Java 9
Casting even empty Objects[] to Integer[] results in:
java.lang.ClassCastException: java.base/[Ljava.lang.Object; cannot be cast to java.base/[Ljava.lang.Integer;
(verified by QueuesTest.toArrayOnZeroQueueShouldNotFailAlsoOnJava9() and
zeroQueueOperations()).

For empty queue. The production implementation was changed (and also slightly
simplified).

The same problem is also with the other Queue implementations. Will be
fixed separately.