Fix the way context-propagation is detected (#3246)
This commit changes the way the context-propagation is detected,
preventing an issue where the boolean would become true while actually
using the registry would throw.

Reactor-Netty CI would fail with a NoClassDefFoundError due to this.